In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('insurance_dataset.csv')
df.head()

,Unnamed: 0,policy_id,age,gender,vehicle_type,vehicle_age,annual_premium,num_claims,claim_amount,feature_1,...,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42
0,0,1,56,male,truck,2,3671.117535,7,75429.963879,51.386653,...,4.699707,82.455588,74.301058,65.804104,83.483757,52.199964,87.548238,23.929053,88.126546,42.483331
1,1,2,69,male,car,1,1545.605412,6,33357.786216,79.664487,...,3.786561,74.200051,85.929448,64.898073,39.717480,90.496702,14.221221,55.674902,64.393126,44.114695
2,2,3,46,female,truck,4,3499.550548,5,71619.141007,33.798155,...,3.165210,98.075295,35.775205,1.854480,10.092992,48.380313,43.528704,28.903443,61.063082,63.408236
3,3,4,32,male,car,14,317.592552,1,7606.223595,70.549002,...,69.764912,53.407485,66.083198,15.227401,79.152976,47.614854,88.848126,39.616004,38.724096,21.653479
4,4,5,60,male,truck,1,1669.459236,6,35278.155506,18.750446,...,53.613547,8.920582,80.204091,85.620269,55.374010,47.039861,14.771202,69.315756,2.813541,33.318385

In [3]:
df = df.iloc[:,1:]
df.shape

(1000, 50)

In [5]:
df.isnull().sum().sum()

0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 50 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   policy_id       1000 non-null   int64
 1   age             1000 non-null   int64
 2   gender          1000 non-null   object
 3   vehicle_type    1000 non-null   object
 4   vehicle_age     1000 non-null   int64
 5   annual_premium  1000 non-null   float64
 6   num_claims      1000 non-null   int64
 7   claim_amount    1000 non-null   float64
 8   feature_1       1000 non-null   float64
 9   feature_2       1000 non-null   float64
 10  feature_3       1000 non-null   float64
 11  feature_4       1000 non-null   float64
 12  feature_5       1000 non-null   float64
 13  feature_6       1000 non-null   float64
 14  feature_7       1000 non-null   float64
 15  feature_8       1000 non-null   float64
 16  feature_9       1000 non-null   float64
 17  feature_10      1000 non-null   float64
 18  feature_11      1000 non-null   float64
 19  feature_12      1000 non-null   float64
 20  feature_13      1000 non-null   float64
 21  feature_14      1000 non-null   float64
 22  feature_15      1000 non-null   float64
 23  feature_16      1000 non-null   float64
 24  feature_17      1000 non-null   float64
 25  feature_18      1000 non-null   float64
 26  feature_19      1000 non-null   float64
 27  feature_20      1000 non-null   float64
 28  feature_21      1000 non-null   float64
 29  feature_22      1000 non-null   float64
 30  feature_23      1000 non-null   float64
 31  feature_24      1000 non-null   float64
 32  feature_25      1000 non-null   float64
 33  feature_26      1000 non-null   float64
 34  feature_27      1000 non-null   float64
 35  feature_28      1000 non-null   float64
 36  feature_29      1000 non-null   float64
 37  feature_30      1000 non-null   float64
 38  feature_31      1000 non-null   float64
 39  feature_32      1000 non-null   float64
 40  feature_33      1000 non-null   float64
 41  feature_34      1000 non-null   float64
 42  feature_35      1000 non-null   float64
 43  feature_36      1000 non-null   float64
 44  feature_37      1000 non-null   float64
 45  feature_38      1000 non-null   float64
 46  feature_39      1000 non-null   float64
 47  feature_40      1000 non-null   float64
 48  feature_41      1000 non-null   float64
 49  feature_42      1000 non-null   float64
dtypes: float64(44), int64(4), object(2)
memory usage: 390.8+ KB

In [7]:
# splitting the data into independent variable and dependent variable
x = df.drop(columns=['policy_id', 'claim_amount'], axis=1)
x.shape

(1000, 48)

In [8]:
y = df['claim_amount']
y.shape

(1000,)

In [9]:
# Define column transformer for preprocessing
numerical_feature = x.select_dtypes(include=['int64','float64']).columns
categorical_feature = x.select_dtypes(include=['object']).columns

In [15]:
numerical_feature

Index(['age', 'vehicle_age', 'annual_premium', 'num_claims', 'feature_1',
       'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6',
       'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11',
       'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16',
       'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21',
       'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26',
       'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31',
       'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36',
       'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41',
       'feature_42'],
      dtype='object')

In [17]:
x[numerical_feature].describe()

,age,vehicle_age,annual_premium,num_claims,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,49.857000,9.990000,2680.915652,4.608000,48.846222,50.391891,51.292774,50.424627,50.035762,48.458416,...,49.521566,50.165629,50.002452,50.143840,50.967243,51.033938,50.105071,50.968364,49.603877,50.317481
std,18.114267,5.541896,1366.469446,2.850344,29.322864,28.500260,29.131623,28.394978,28.940881,28.961167,...,28.484796,29.073693,28.970386,29.151076,29.170810,29.118933,29.025365,28.688671,29.095515,28.412395
min,18.000000,1.000000,202.125351,0.000000,0.062752,0.160119,0.181203,0.135552,0.018520,0.102230,...,0.083636,0.020317,0.096369,0.136536,0.031445,0.404443,0.009327,0.192418,0.220395,0.122299
25%,35.000000,5.000000,1533.866660,2.000000,22.528288,26.578832,26.328031,26.609260,26.137697,24.420998,...,24.905663,26.365356,25.806347,25.066327,25.965889,25.885157,25.251510,25.968352,24.251964,26.369119
50%,50.000000,10.000000,2752.319542,5.000000,49.068564,50.988241,52.242859,50.973482,49.653686,48.087985,...,48.841580,49.378119,49.984326,49.326604,51.195838,50.603456,50.626251,52.007184,49.879127,50.818910
75%,66.000000,15.000000,3854.688740,7.000000,73.019523,74.730535,77.117121,75.769905,74.180312,73.124886,...,74.589511,73.684246,75.976295,75.729745,77.155239,76.893006,75.596095,76.619673,74.023583,74.583449
max,79.000000,19.000000,4997.810810,9.000000,99.984924,99.975156,99.974127,99.931627,99.949635,99.963563,...,99.751500,99.942852,99.918657,99.898460,99.876357,99.578877,99.979711,99.914675,99.850311,99.810747

In [10]:
len(numerical_feature)

46

In [11]:
len(categorical_feature)

2

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [18]:
preprocessor = ColumnTransformer(transformers=[('num', StandardScaler(), numerical_feature),
                                               ('cat', OneHotEncoder(), categorical_feature)])

In [19]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['age', 'vehicle_age', 'annual_premium', 'num_claims', 'feature_1',
       'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6',
       'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11',
       'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16',
       'feature_17', 'feature_18', 'feature_19'...
       'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26',
       'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31',
       'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36',
       'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41',
       'feature_42'],
      dtype='object')),
                                ('cat', OneHotEncoder(),
                                 Index(['gender', 'vehicle_type'], dtype='object'))])

In [28]:
# splitting the data into training and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
x_train

,age,gender,vehicle_type,vehicle_age,annual_premium,num_claims,feature_1,feature_2,feature_3,feature_4,...,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42
29,38,male,truck,5,2835.106157,9,69.012312,66.033583,58.507782,83.249870,...,81.676499,7.239289,55.269802,75.261199,82.492724,87.449179,70.433243,46.245108,48.159958,43.276940
535,31,female,car,17,4707.474061,6,85.312817,6.969070,66.918365,19.570775,...,39.331220,85.523334,38.786799,41.793875,16.095728,38.744334,3.027250,36.574549,22.290187,54.954985
695,68,male,car,7,3818.552354,3,10.626590,1.340945,12.989880,26.623349,...,1.172312,74.485953,78.775043,54.515724,63.641286,99.511116,39.849440,79.336128,56.971739,10.092868
557,59,female,truck,15,4074.508730,5,40.689843,15.892477,97.742295,10.730121,...,72.948009,72.300057,27.792890,34.777679,46.659354,65.107317,64.084862,22.063028,29.112364,62.524505
836,63,female,motorcycle,5,1242.708255,3,69.251401,87.216115,92.654778,79.618595,...,15.717803,61.321614,68.203899,70.016422,62.585351,34.960651,96.227504,94.601693,53.240694,94.395996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,32,female,car,8,3899.746968,1,81.609235,35.978941,72.547803,11.040950,...,15.275256,68.879889,94.630308,9.141270,64.620419,12.629630,37.118390,24.755753,86.606118,22.731958
270,75,female,motorcycle,7,4304.993528,3,96.655892,26.308003,64.019387,30.600097,...,26.303692,61.488300,65.294239,98.850924,52.194302,13.739350,17.715826,4.575304,58.779730,31.701961
860,21,female,truck,15,3436.442442,9,15.915908,14.282411,25.325282,15.406165,...,20.288114,99.150144,5.189408,17.424931,77.115269,50.699103,88.487954,40.170387,38.995894,53.034963
435,47,female,truck,14,668.068763,5,90.610093,9.976356,41.521376,60.534363,...,46.491137,40.117542,91.288754,78.265825,13.258171,21.324872,53.318145,81.000003,77.454397,49.596618
102,53,male,truck,16,4355.936793,0,86.623287,54.007932,54.418315,78.195262,...,77.833635,58.844330,35.946663,41.162003,93.530721,47.167093,52.156274,16.408960,40.707120,6.250170

In [30]:
from scipy.stats import pearsonr

In [31]:
# correlation analysis

correlations = {}
for col in numerical_feature:
    corr, _ = pearsonr(x[col], y)
    correlations[col] = corr

In [32]:
correlations

{'age': 0.07716121305041079,
 'vehicle_age': -0.0159607581739013,
 'annual_premium': 0.999731580833913,
 'num_claims': -0.010707268573059803,
 'feature_1': 0.05137717319254567,
 'feature_2': 0.02367058142640543,
 'feature_3': 0.017066400967332924,
 'feature_4': 0.010673090523762183,
 'feature_5': -0.03259644234892623,
 'feature_6': -0.06757797843737247,
 'feature_7': -0.02877326392337091,
 'feature_8': -0.05244683226340418,
 'feature_9': 0.0441650711308645,
 'feature_10': -0.05896651282299013,
 'feature_11': 0.012291060764136856,
 'feature_12': -0.018372341494662228,
 'feature_13': 0.0025523521574060543,
 'feature_14': 0.053300593771369933,
 'feature_15': 0.036040035606415194,
 'feature_16': 0.008902988933259571,
 'feature_17': 0.02189713868817563,
 'feature_18': -0.020814048202977407,
 'feature_19': 0.006474115948059427,
 'feature_20': -0.012412207052737602,
 'feature_21': -0.009744548789629812,
 'feature_22': 0.021057663673815064,
 'feature_23': 0.00936276328831853,
 'feature_24': -0.008827651933094547,
 'feature_25': -0.0010602238429931882,
 'feature_26': -0.036972105200642216,
 'feature_27': 0.007397426025321299,
 'feature_28': 0.012140975044160654,
 'feature_29': 0.005734365332127754,
 'feature_30': 0.053369357269133416,
 'feature_31': 0.0021922616447023636,
 'feature_32': -0.020246266643922785,
 'feature_33': 0.010025140207141773,
 'feature_34': 0.057707457007073845,
 'feature_35': -0.051201289255606255,
 'feature_36': -0.03784071086234011,
 'feature_37': 0.059979576083701594,
 'feature_38': 0.030163308417509364,
 'feature_39': -0.029842863131793115,
 'feature_40': 0.02395803387721563,
 'feature_41': 0.07171625805595888,
 'feature_42': 0.004709790143460119}

In [37]:
# Chi-Square Test
from scipy.stats import chi2_contingency
chi2_result = {}

for col in categorical_feature:
    contingency_table = pd.crosstab(x[col], y)
    chi2,p,_,_ = chi2_contingency(contingency_table)
    chi2_result[col]= (chi2, p)    

print("\nChi-Square Test:")
for key, value in chi2_result.items():
    print(f"{key}: chi2={value[0]:.4f}, p-value={value[1]:.4f}")

Chi-Square Test:
gender: chi2=1000.0000, p-value=0.4851
vehicle_type: chi2=2000.0000, p-value=0.4832

In [36]:
chi2_result

{'gender': (1000.0000000000001, 0.48513148927490046),
 'vehicle_type': (2000.0, 0.483180144471063)}

In [40]:
# ANOVA Test
from scipy.stats import f_oneway
anova_results = {}
for col in categorical_feature:
    categories = x[col].unique()
    groups = [y[x[col]==category] for category in categories]
    f_val, p_val = f_oneway(*groups)
    anova_results[col] = (f_val, p_val)

print("\nANOVA Test:")
for key, value in anova_results.items():
    print(f"{key}: F = {value[0]:.4f}, p-value = {value[1]:.4f}")

ANOVA Test:
gender: F = 4.8047, p-value = 0.0286
vehicle_type: F = 0.4899, p-value = 0.6128

In [ ]:
# Mutual Information
# variance inflation factor
# Permutation method
# T-test, Z-Test
# Feature importance - random forest, gradient boosting etc...
# PCA 
# RFE technique (recursive Feature Elimination)
# LDA

# Pipeline
# model building - all regression model
# hyperparameter
# best model